"""HTML report (multi-language)."""
from __future__ import annotations

from pathlib import Path

from yueshang_aoi.core.result import InspectionResult

_I18N = {
    "zh": {
        "title": "AOI 检测报告",
        "summary": "总览",
        "product": "产品",
        "profile": "Profile",
        "status": "结果",
        "ok": "合格 (OK)",
        "ng": "不合格 (NG)",
        "total": "总部件数",
        "ok_count": "合格数",
        "ng_count": "不合格数",
        "elapsed": "耗时 (s)",
        "defect_summary": "缺陷分布",
        "parts_table": "部件明细",
        "part_id": "部件ID",
        "class": "类别",
        "bbox": "位置",
        "defect": "缺陷类型",
        "confidence": "置信度",
        "trigger": "触发路由",
        "no_defects": "未发现缺陷",
        "footer": "由鑫晨科技 XinchenAOI 平台生成",
    },
    "en": {
        "title": "AOI Inspection Report",
        "summary": "Summary",
        "product": "Product",
        "profile": "Profile",
        "status": "Status",
        "ok": "PASS (OK)",
        "ng": "FAIL (NG)",
        "total": "Total Parts",
        "ok_count": "OK Count",
        "ng_count": "NG Count",
        "elapsed": "Elapsed (s)",
        "defect_summary": "Defect Distribution",
        "parts_table": "Part Details",
        "part_id": "Part ID",
        "class": "Class",
        "bbox": "Bounding Box",
        "defect": "Defect Type",
        "confidence": "Confidence",
        "trigger": "Triggered Route",
        "no_defects": "No defects detected",
        "footer": "Generated by Xinchen Technology · XinchenAOI Platform",
    },
    "es": {
        "title": "Informe de Inspección AOI",
        "summary": "Resumen",
        "product": "Producto",
        "profile": "Perfil",
        "status": "Estado",
        "ok": "APROBADO (OK)",
        "ng": "RECHAZADO (NG)",
        "total": "Piezas totales",
        "ok_count": "Aprobadas",
        "ng_count": "Rechazadas",
        "elapsed": "Tiempo (s)",
        "defect_summary": "Distribución de defectos",
        "parts_table": "Detalle de piezas",
        "part_id": "ID de pieza",
        "class": "Clase",
        "bbox": "Caja",
        "defect": "Tipo de defecto",
        "confidence": "Confianza",
        "trigger": "Ruta activada",
        "no_defects": "No se detectaron defectos",
        "footer": "Generado por Xinchen Technology · Plataforma XinchenAOI",
    },
    "pt": {
        "title": "Relatório de Inspeção AOI",
        "summary": "Resumo",
        "product": "Produto",
        "profile": "Perfil",
        "status": "Status",
        "ok": "APROVADO (OK)",
        "ng": "REPROVADO (NG)",
        "total": "Total de peças",
        "ok_count": "Aprovadas",
        "ng_count": "Reprovadas",
        "elapsed": "Tempo (s)",
        "defect_summary": "Distribuição de defeitos",
        "parts_table": "Detalhes das peças",
        "part_id": "ID da peça",
        "class": "Classe",
        "bbox": "Caixa",
        "defect": "Tipo de defeito",
        "confidence": "Confiança",
        "trigger": "Rota ativada",
        "no_defects": "Nenhum defeito detectado",
        "footer": "Gerado pela Xinchen Technology · Plataforma XinchenAOI",
    },
}


def write_html_report(result: InspectionResult, output_dir: Path, lang: str = "zh") -> Path:
    t = _I18N.get(lang, _I18N["en"])
    status_color = "#16a34a" if result.overall_status == "OK" else "#dc2626"
    status_label = t["ok"] if result.overall_status == "OK" else t["ng"]

    parts_rows = []
    for p in result.parts:
        if not p.is_ng:
            continue
        parts_rows.append(
            f"<tr><td>{p.part_id}</td><td>{p.part_class or '-'}</td>"
            f"<td>{p.bbox}</td><td><span class='tag-ng'>{p.final_defect_type or '-'}</span></td>"
            f"<td>{p.final_confidence:.2f}</td><td>{p.triggered_route or '-'}</td></tr>"
        )
    if not parts_rows:
        parts_rows.append(f"<tr><td colspan='6' class='empty'>{t['no_defects']}</td></tr>")

    summary_rows = "".join(
        f"<li><b>{k}</b>: {v}</li>" for k, v in result.defect_summary.items()
    ) or f"<li class='empty'>{t['no_defects']}</li>"

    html = f"""<!doctype html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<title>{t['title']} - {result.product_id}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", system-ui, sans-serif; margin: 32px; color: #0f172a; }}
  h1 {{ font-size: 22px; margin: 0 0 12px; }}
  .meta {{ color: #64748b; font-size: 13px; margin-bottom: 24px; }}
  .status {{ display: inline-block; padding: 6px 14px; border-radius: 999px;
            color: white; background: {status_color}; font-weight: 600; }}
  .grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0 24px; }}
  .card {{ background: #f8fafc; padding: 14px; border-radius: 10px; border: 1px solid #e2e8f0; }}
  .card .k {{ color: #64748b; font-size: 12px; }}
  .card .v {{ font-size: 22px; font-weight: 700; margin-top: 4px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
  th, td {{ text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0; }}
  th {{ background: #f1f5f9; }}
  .tag-ng {{ color: #b91c1c; background: #fee2e2; padding: 2px 8px; border-radius: 6px; font-size: 12px; }}
  .empty {{ color: #94a3b8; }}
  ul {{ list-style: none; padding: 0; margin: 0; }} li {{ padding: 4px 0; }}
  footer {{ margin-top: 36px; color: #94a3b8; font-size: 12px; text-align: center; }}
</style>
</head>
<body>
<h1>{t['title']}</h1>
<div class="meta">
  {t['product']}: <b>{result.product_id}</b> · {t['profile']}: {result.profile_name} ·
  {result.timestamp}
</div>
<div class="status">{t['status']}: {status_label}</div>

<div class="grid">
  <div class="card"><div class="k">{t['total']}</div><div class="v">{result.total_parts}</div></div>
  <div class="card"><div class="k">{t['ok_count']}</div><div class="v" style="color:#16a34a">{result.ok_count}</div></div>
  <div class="card"><div class="k">{t['ng_count']}</div><div class="v" style="color:#dc2626">{result.ng_count}</div></div>
  <div class="card"><div class="k">{t['elapsed']}</div><div class="v">{result.elapsed_seconds:.2f}</div></div>
</div>

<h2>{t['defect_summary']}</h2>
<ul>{summary_rows}</ul>

<h2>{t['parts_table']}</h2>
<table>
  <thead><tr>
    <th>{t['part_id']}</th><th>{t['class']}</th><th>{t['bbox']}</th>
    <th>{t['defect']}</th><th>{t['confidence']}</th><th>{t['trigger']}</th>
  </tr></thead>
  <tbody>{''.join(parts_rows)}</tbody>
</table>

<footer>{t['footer']}</footer>
</body>
</html>
"""
    out = output_dir / f"{result.product_id}.{lang}.html"
    out.write_text(html, encoding="utf-8")
    return out
